In [2]:
!gdown 1Jy76NPwbPgVmWJZtIuanczNumzv15Iq2

Downloading...
From: https://drive.google.com/uc?id=1Jy76NPwbPgVmWJZtIuanczNumzv15Iq2
To: /content/bookings.csv
100% 12.2M/12.2M [00:00<00:00, 169MB/s]

## Бронирование отелей (мини проект)

**Импорт набора данных из csv-файла в рабочем каталоге**

In [3]:
import pandas as pd

bookings = pd.read_csv('bookings.csv', sep=';')

**Проверка количества строк и столбцов в наборе данных**

In [4]:
bookings.shape

(119390, 21)

**Проверка имен столбцов**

In [8]:
bookings.columns

Index(['Hotel', 'Is Canceled', 'Lead Time', 'arrival full date',
       'Arrival Date Year', 'Arrival Date Month', 'Arrival Date Week Number',
       'Arrival Date Day of Month', 'Stays in Weekend nights',
       'Stays in week nights', 'stays total nights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'Reserved Room Type', 'Assigned room type',
       'customer type', 'Reservation Status', 'Reservation status_date'],
      dtype='object')

**bookings.csv -- data description:**
* Hotel – тип отеля (City Hotel/Resort Hotel)  
* Is canceled – отменена ли бронь (1/0)  
* Lead time – количество дней между датой бронирования и датой прибытия        
* Arrival full date – полная дата прибытия
* Arrival date year – год прибытия    
* Arrival date month – месяц прибытия  
* Arrival date week number –  номер недели прибытия
* Arrival date day of month – дата заезда, день месяца
* Stays in weekend nights – ночи выходного дня  
* Stays in week nights – ночи рабочей недели (пн - чт)  
* Stays total nights – всего ночей    
* Adults – количество взрослых    
* Children – количество детей
* Babies – количество малышей    
* Meal – тип питания, включенный в бронирование  
* Country – страна проживания посетителя   
* Reserved room type – тип забронированного номера    
* Assigned room type – тип предоставленного номера
* Customer type – тип клиента
* Reservation status – статус бронирования: Canceled; Check-Out; No-Show  
* Reservation status date – дата последнего обновления статуса

**Checking columns datatypes**

In [ ]:
bookings.dtypes

Hotel                         object
Is Canceled                    int64
Lead Time                      int64
arrival full date             object
Arrival Date Year              int64
Arrival Date Month            object
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                          object
Country                       object
Reserved Room Type            object
Assigned room type            object
customer type                 object
Reservation Status            object
Reservation status_date       object
dtype: object

**Поиск наиболее часто встречающегося типа данных**

In [9]:
bookings.dtypes.value_counts()

object     10
int64      10
float64     1
Name: count, dtype: int64

**Проверка первых семи строк набора данных**

In [10]:
bookings.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

**Краткая сводка по данным**

In [11]:
bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Hotel                      119390 non-null  object
 1   Is Canceled                119390 non-null  int64
 2   Lead Time                  119390 non-null  int64
 3   arrival full date          119390 non-null  object
 4   Arrival Date Year          119390 non-null  int64
 5   Arrival Date Month         119390 non-null  object
 6   Arrival Date Week Number   119390 non-null  int64
 7   Arrival Date Day of Month  119390 non-null  int64
 8   Stays in Weekend nights    119390 non-null  int64
 9   Stays in week nights       119390 non-null  int64
 10  stays total nights         119390 non-null  int64
 11  Adults                     119390 non-null  int64
 12  Children                   119386 non-null  float64
 13  Babies                     119390 non-null  int64
 14  Meal                       119390 non-null  object
 15  Country                    118902 non-null  object
 16  Reserved Room Type         119390 non-null  object
 17  Assigned room type         119390 non-null  object
 18  customer type              119390 non-null  object
 19  Reservation Status         119390 non-null  object
 20  Reservation status_date    119390 non-null  object
dtypes: float64(1), int64(10), object(10)
memory usage: 19.1+ MB

**Замена пробелов в названиях столбцов**

In [12]:
def name_upd(name):
    return name.replace(' ', '_').lower()

bookings = bookings.rename(columns=name_upd)

bookings

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017-08-30,2017,August,35,30,2,5,...,2,0.0,0,BB,BEL,A,A,Transient,Check-Out,2017-09-06
119386,City Hotel,0,102,2017-08-31,2017,August,35,31,2,5,...,3,0.0,0,BB,FRA,E,E,Transient,Check-Out,2017-09-07
119387,City Hotel,0,34,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,DEU,D,D,Transient,Check-Out,2017-09-07
119388,City Hotel,0,109,2017-08-31,2017,August,35,31,2,5,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-07
119389,City Hotel,0,205,2017-08-29,2017,August,35,29,2,7,...,2,0.0,0,HB,DEU,A,A,Transient,Check-Out,2017-09-07

**Топ-5 стран по бронированиям среди жителей**

In [13]:
successful_bookings_top5 = bookings.query('is_canceled == 0') \
    .groupby('country') \
    .agg({'is_canceled': 'count'}) \
    .sort_values('is_canceled', ascending=False).head() \
    .rename(columns={'is_canceled': 'successful bookings'})


successful_bookings_top5

         successful bookings
country
PRT                    21071
GBR                     9676
FRA                     8481
ESP                     6391
DEU                     6069

**Среднее количество ночей проживания в зависимости от типа отеля.**

In [14]:
bookings.groupby('hotel') \
    .agg({'stays_total_nights': 'mean'}) \
    .round(2)

              stays_total_nights
hotel
City Hotel                  2.98
Resort Hotel                4.32

**Случаи, когда зарезервированный тип номера отличается от назначенного типа номера.**

In [15]:
occasions = bookings.rename(columns={'is_canceled': 'occasions'}) \
                    .query('assigned_room_type != reserved_room_type') \
                    .agg({'occasions': 'count'})

occasions

occasions    14917
dtype: int64

**Анализ планируемой даты заезда. Какой месяц был самым популярным в 2016 году? 2017?**

In [26]:
for year in [2016, 2017]:
      max_is_canceled = bookings.query("arrival_date_year == @year and is_canceled == 0")\
            .groupby(['arrival_date_year', 'arrival_date_month'], as_index=False)\
            .agg({'is_canceled': 'count'})
      message = "Самый популярный месяц в {}:"
      print(message.format(year), max_is_canceled['arrival_date_month']
            .loc[max_is_canceled.is_canceled.idxmax(axis=0)])

Самый популярный месяц в 2016: October
Самый популярный месяц в 2017: May

**Самый популярный месяц для отмены бронирования в 2015? 2016? 2017 годах?**

In [25]:
import warnings
warnings.filterwarnings('ignore')

for year in [2015, 2016, 2017]:
    max_canceled_month = bookings.query('is_canceled == 1 and arrival_date_year == @year') \
    .groupby(['arrival_date_year', 'arrival_date_month']) \
    .agg({'is_canceled': 'count'}) \
    .idxmax()
    print(f'Большинство отмен бронирований в {year} произошло в {max_canceled_month[0][1]}.')

Большинство отмен бронирований в 2015 произошло в September.
Большинство отмен бронирований в 2016 произошло в October.
Большинство отмен бронирований в 2017 произошло в May.

**Какой столбец имеет наибольшее среднее значение: взрослые, дети, младенцы?**

In [27]:
bookings[['adults', 'children', 'babies']].mean()

adults      1.856403
children    0.103890
babies      0.007949
dtype: float64

**Создайте новый столбец "total_kids", добавив в него количество детей и количество младенцев. У какого типа отелей наибольшее среднее значение total_kids?**

In [30]:
# Создайте колонку total_kids, объединив столбцы children и babies.
# Для отелей какого типа среднее значение переменной оказалось наибольшим?
bookings['total_kids'] = bookings.children + bookings.babies

bookings.groupby('hotel', as_index=False) \
    .agg({'total_kids' : 'mean'}) \
    .round(2) \
    .max()

hotel         Resort Hotel
total_kids            0.14
dtype: object

**Коэффициент оттока** - это скорость, с которой клиенты прекращают вести бизнес с организацией. Чаще всего он выражается как процент подписчиков услуг, которые прекращают свои подписки в течение заданного периода времени. Это также скорость, с которой сотрудники покидают свои рабочие места в течение определенного периода. Чтобы компания расширяла свою клиентуру, темпы ее роста (измеряемые количеством новых клиентов) должны превышать уровень оттока.

**Рассчитайте коэффициент оттока для клиентов с детьми и клиентов, у которых детей нет.**

In [32]:
# создание нового столбца
bookings['has_kids'] = bookings.total_kids > 0

# запрос количества случаев отмены бронирования для посетителей с детьми и без них
canceled_with_kids = bookings.query('has_kids == True and is_canceled == 1') \
    .is_canceled.value_counts()
canceled_no_kids = bookings.query('has_kids == False and is_canceled == 1') \
    .is_canceled.value_counts()

# итоговые значения для расчета скорости оттока
canceled_no_kids_int = canceled_no_kids[1]
canceled_with_kids_int = canceled_with_kids[1]
total_bookings_with_kids = len(bookings.query('has_kids == True'))
total_bookings_no_kids = len(bookings.query('has_kids == False'))

# функция для расчета скорости оттока
def churn_rate(total, canceled):
    return (canceled / total) * 100


print(f'Уровень оттока клиентов, у которых нет детей: {round(churn_rate(total_bookings_no_kids, canceled_no_kids_int), 2)}')
print(f'Уровень оттока клиентов с детьми: {round(churn_rate(total_bookings_with_kids, canceled_with_kids_int), 2)}')

Уровень оттока клиентов, у которых нет детей: 37.22
Уровень оттока клиентов с детьми: 34.92